import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Frontend Mentor | Interactive comments section</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <main>hello</main>
    </div>
  );
}
