import Head from "next/head";
import Comments from "../components/Comments";
import { useUser } from "../context/DataContext";
import Main from "../styles/styles";

export default function Home() {
  const user = useUser();
  return (
    <div>
      <Head>
        <title>Frontend Mentor | Interactive comments section</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <Main>
        <div className="container">
          <Comments />
        </div>
      </Main>
    </div>
  );
}
